CREATE TABLE IF NOT EXISTS `food` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `name` VARCHAR(100) NOT NULL COMMENT '菜品名称',
    `type` VARCHAR(50) NOT NULL COMMENT '菜品类别',
    `description` VARCHAR(255) DEFAULT NULL COMMENT '描述',
    `is_valid` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否有效，1=有效，0=失效',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_food_valid` (`is_valid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='今日吃什么 - 菜品表';

CREATE TABLE IF NOT EXISTS `user_account` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `username` VARCHAR(60) NOT NULL COMMENT '用户名唯一',
    `nickname` VARCHAR(100) NOT NULL COMMENT '昵称',
    `password` VARCHAR(255) NOT NULL COMMENT '加密密码',
    `is_valid` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否有效',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_user_username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='妙妙屋用户';

